title: "Jakhongir Saydaliev"
url: "https://jakhongir0103.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://jakhongir0103.github.io"
footer_text: "Fin"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "./index.md"
 - name: "Blogs"
   link: "./posts/blogs.md"
 - name: "Resume"
   link: "resume.pdf"
