title: "Jakhongir Saydaliev"
url: "https://jakhongir0103.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://jakhongir0103.github.io"
footer_text: "End"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/index"
 - name: "Blogs"
   link: "/blogs"
 - name: "CV"
   link: "/cv.pdf"
